import type { MarkdownToolbarButton } from '@/types';

export const markdownButtons: MarkdownToolbarButton[] = [
  {
    icon: 'text',
    label: 'H1',
    insertBefore: '# ',
    insertAfter: '',
    placeholder: '見出し',
  },
  {
    icon: 'text',
    label: 'H2',
    insertBefore: '## ',
    insertAfter: '',
    placeholder: '見出し',
  },
  {
    icon: 'text',
    label: 'H3',
    insertBefore: '### ',
    insertAfter: '',
    placeholder: '見出し',
  },
  {
    icon: 'text',
    label: '**',
    insertBefore: '**',
    insertAfter: '**',
    placeholder: '太字',
  },
  {
    icon: 'text',
    label: '*',
    insertBefore: '*',
    insertAfter: '*',
    placeholder: '斜体',
  },
  {
    icon: 'code-slash',
    label: '`',
    insertBefore: '`',
    insertAfter: '`',
    placeholder: 'コード',
  },
  {
    icon: 'code-working',
    label: '```',
    insertBefore: '```\n',
    insertAfter: '\n```',
    placeholder: 'コードブロック',
  },
  {
    icon: 'link',
    label: 'Link',
    insertBefore: '[',
    insertAfter: '](url)',
    placeholder: 'リンクテキスト',
  },
  {
    icon: 'list',
    label: '-',
    insertBefore: '- ',
    insertAfter: '',
    placeholder: 'リスト項目',
  },
  {
    icon: 'list',
    label: '1.',
    insertBefore: '1. ',
    insertAfter: '',
    placeholder: 'リスト項目',
  },
  {
    icon: 'chatbox-outline',
    label: '>',
    insertBefore: '> ',
    insertAfter: '',
    placeholder: '引用',
  },
  {
    icon: 'image',
    label: 'IMG',
    insertBefore: '![',
    insertAfter: '](url)',
    placeholder: '画像の説明',
  },
  {
    icon: 'remove',
    label: '---',
    insertBefore: '\n---\n',
    insertAfter: '',
  },
];
